# @package suite
defaults:
  - _self_
  - task: ur5e_task

suite: ur5e_suite
name: ur5e_suite

# task settings
frame_stack: 1
action_repeat: 1
discount: 0.99
hidden_dim: 256

# train settings
num_train_steps: 601000
log_every_steps: 1000
save_every_steps: 50000
history: true
history_len: 10

# eval
eval_every_steps: 200000
num_eval_episodes: 5
eval_history_len: 10

# data loading
action_after_steps: 1 #8

# obs_keys
# pixel_keys: ["pixels0", "pixels1", "pixels2", "pixels3"]
# depth_keys: ["depth0", "depth1", "depth2", "depth3"]
pixel_keys: ["pixels"]
depth_keys: ["depths"]

proprio_key: "proprioceptive"
feature_key: "features"

# snapshot
save_snapshot: true

task_make_fn:
  _target_: suite.ur5e_suite.make
  # suite: ${suite.task.suite}
  # scenes: ${suite.task.scenes}
  # tasks: ${suite.task.tasks}
  frame_stack: ${suite.frame_stack}
  action_repeat: ${suite.action_repeat}
  height: 128
  width: 128
  max_episode_len: ??? # to be specified later
  max_state_dim: ??? # to be specified later
  depth_keys: ${suite.depth_keys}
  eval_task_name: ${eval_task_name}
  training: ${training}
  relative_actions: ${relative_actions}
